INSERT INTO public.estados_brasileiros (id, abreviacao, nome) VALUES (1, 'AC', 'Acre');
INSERT INTO public.estados_brasileiros (id, abreviacao, nome) VALUES (2, 'AL', 'Alagoas');
INSERT INTO public.estados_brasileiros (id, abreviacao, nome) VALUES (3, 'AP', 'Amapá');
INSERT INTO public.estados_brasileiros (id, abreviacao, nome) VALUES (4, 'AM', 'Amazonas');
INSERT INTO public.estados_brasileiros (id, abreviacao, nome) VALUES (5, 'BA', 'Bahia');
INSERT INTO public.estados_brasileiros (id, abreviacao, nome) VALUES (6, 'CE', 'Ceará');
INSERT INTO public.estados_brasileiros (id, abreviacao, nome) VALUES (7, 'DF', 'Distrito Federal');
INSERT INTO public.estados_brasileiros (id, abreviacao, nome) VALUES (8, 'ES', 'Espírito Santo');
INSERT INTO public.estados_brasileiros (id, abreviacao, nome) VALUES (9, 'GO', 'Goiás');
INSERT INTO public.estados_brasileiros (id, abreviacao, nome) VALUES (10, 'MA', 'Maranhão');
INSERT INTO public.estados_brasileiros (id, abreviacao, nome) VALUES (11, 'MT', 'Mato Grosso');
INSERT INTO public.estados_brasileiros (id, abreviacao, nome) VALUES (12, 'MS', 'Mato Grosso do Sul');
INSERT INTO public.estados_brasileiros (id, abreviacao, nome) VALUES (13, 'MG', 'Minas Gerais');
INSERT INTO public.estados_brasileiros (id, abreviacao, nome) VALUES (14, 'PA', 'Pará');
INSERT INTO public.estados_brasileiros (id, abreviacao, nome) VALUES (15, 'PB', 'Paraíba');
INSERT INTO public.estados_brasileiros (id, abreviacao, nome) VALUES (16, 'PR', 'Paraná');
INSERT INTO public.estados_brasileiros (id, abreviacao, nome) VALUES (17, 'PE', 'Pernambuco');
INSERT INTO public.estados_brasileiros (id, abreviacao, nome) VALUES (18, 'PI', 'Piauí');
INSERT INTO public.estados_brasileiros (id, abreviacao, nome) VALUES (19, 'RJ', 'Rio de Janeiro');
INSERT INTO public.estados_brasileiros (id, abreviacao, nome) VALUES (20, 'RN', 'Rio Grande do Norte');
INSERT INTO public.estados_brasileiros (id, abreviacao, nome) VALUES (21, 'RS', 'Rio Grande do Sul');
INSERT INTO public.estados_brasileiros (id, abreviacao, nome) VALUES (22, 'RO', 'Rondônia');
INSERT INTO public.estados_brasileiros (id, abreviacao, nome) VALUES (23, 'RR', 'Roraima');
INSERT INTO public.estados_brasileiros (id, abreviacao, nome) VALUES (24, 'SC', 'Santa Catarina');
INSERT INTO public.estados_brasileiros (id, abreviacao, nome) VALUES (25, 'SP', 'São Paulo');
INSERT INTO public.estados_brasileiros (id, abreviacao, nome) VALUES (26, 'SE', 'Sergipe');
INSERT INTO public.estados_brasileiros (id, abreviacao, nome) VALUES (27, 'TO', 'Tocantins');